noun = input("Noun: ")
state = input("State: ")
verb = input("Verb: ")
noun2 = input("Noun: ")
print ("A " + noun + " in " + state + " was arrested this morning after he " + verb + " a in front of " + noun2 + ".")

propername = input("Proper Name: ")
verb2 = input("Verb: ")
noun3 = input("Noun: ")
verb3 = input("Verb: ")
noun4 = input("Noun: ")
body = input("Part of Body: ")
print (propername + ", had a history of " + verb2 + ", but no one-not even his " + noun3 + "-ever imagined he'd " + verb3 + " with a " + noun4 + " stuck in his " + body + ".")

adjective = input("Adjective: ")
relative = input("Relative: ")
print("I always thought he was " + adjective + ", but I never thought he'd so something like this. Even his " + relative + " was surprised.")

activity = input("Activity: ")
restuarant = input("Chain Restuarant: ")
adjectivepasttense = input("Adjective, Past Tense: ")
print("After a brief " + activity + ", cops followed him to a " + restuarant + ", where he reportedly " + adjectivepasttense + " in the fry machine." )

month = input("Month: ")
verb4 = input("Verb: ")
noun5 = input("Noun: ")
verb5 = input("Verb: Past Tense: ")
adjective2 = input("Adjective: ")
print("In " + month + ", a woman was charged with a similar crime. But rather than " + verb4 + " with a " + noun5 + ", she " + verb5 + " with a " + adjective2 + " dog.")

verb6 = input("Verb: ")
noun6 = input("Noun: ")
noun7 = input("Plural Noun: ")
print("Either way, we imagine that after witnessing him " + verb6 + " with a " + noun6 + " there are probably a whole lot of " + noun7 + " that are going to need some therapy." )

print("Your Story: ")
print ("A " + noun + " in " + state + " was arrested this morning after he " + verb + " a in front of " + noun2 + ".")
print (propername + ", had a history of " + verb2 + ", but no one-not even his " + noun3 + "-ever imagined he'd " + verb3 + " with a " + noun4 + " stuck in his " + body + ".")
print("I always thought he was " + adjective + ", but I never thought he'd so something like this. Even his " + relative + " was surprised.")
print("After a brief " + activity + ", cops followed him to a " + restuarant + ", where he reportedly " + adjectivepasttense + " in the fry machine." )
print("In " + month + ", a woman was charged with a similar crime. But rather than " + verb4 + " with a " + noun5 + ", she " + verb5 + " with a " + adjective2 + " dog.")
print("Either way, we imagine that after witnessing him " + verb6 + " with a " + noun6 + " there are probably a whole lot of " + noun7 + " that are going to need some therapy." )
